CREATE TABLE Addresses (
	Id				INT				IDENTITY(1,1) PRIMARY KEY,
	Street			NVARCHAR(100)	NULL,
	Number			NVARCHAR(50)	NULL,
	PostalCode		NVARCHAR(20)	NULL,
	City			NVARCHAR(50)	NULL,
	Country			NVARCHAR(50)	NULL
);