CREATE TABLE Customers (
	CustomerId		INT				PRIMARY KEY IDENTITY(1000,1),
    PersonId		INT				NOT NULL,
	LastPurchaseAt	DATETIME2		NULL,
	FOREIGN KEY (PersonId) REFERENCES Persons(Id)
		ON DELETE CASCADE
);